### PR TITLE
feat: enable to build with both ros1 and ros2

### LINKED ISSUE #14: Noetic Release is failing
@esteve I am happy to helps support releasing version of this and qpoasis. Would you be open t adding me as a maintainer to perform releases? 

It looks like qpoasis_vender released fine but osqp_vender has an issue.

### PR DESCRIPTION
**Pull request by wep21**
Closes #14 #15

### CODE REVIEW

**Comment by wep21** [comment]
@ipa-danb @Levi-Armstrong @esteve 
Could you review this PR? This PR enables to build the package with both ros1 and ros2 and modify noetic build. I will create a release for noetic after this PR is merged.

**Review by Levi-Armstrong — APPROVED** [review]
LGTM

**Comment by ipa-danb** [comment]
LGTM, too

**Comment by Levi-Armstrong** [comment]
@wep21 Thanks for making the fix!

**Review by esteve — APPROVED** [review]
LGTM

**Pull request merged**
